databases:
  - name:  mine
    databaseName: mine_development
    user: mine

services:
  - type: web
    name: mine
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mine
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false